"""next change

Revision ID: 68b5225daada
Revises: c8a8335652a9
Create Date: 2026-02-02 09:55:06.960011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b5225daada'
down_revision: Union[str, Sequence[str], None] = 'c8a8335652a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint(op.f('books_isbn_key'), 'books', type_='unique')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_unique_constraint(op.f('books_isbn_key'), 'books', ['isbn'], postgresql_nulls_not_distinct=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('books', 'author_id')
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.drop_table('genres')
    op.drop_table('authors')
    # ### end Alembic commands ###
