"""add created_by to books

Revision ID: b194cea3fe05
Revises: 081b45ad4315
Create Date: 2026-02-03 15:47:24.142556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b194cea3fe05'
down_revision: Union[str, Sequence[str], None] = '081b45ad4315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
