"""add created_by to books

Revision ID: bdf51b18f128
Revises: 8f9e406acf50
Create Date: 2026-02-03 16:02:41.964973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf51b18f128'
down_revision: Union[str, Sequence[str], None] = '8f9e406acf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('books_created_by_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['created_by_id'], ['id'])
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_created_by_fkey'), 'books', 'users', ['created_by'], ['id'])
    op.drop_column('books', 'created_by_id')
    # ### end Alembic commands ###
